### ISSUE TITLE
[2.0] Roadmap for 2.0

### ISSUE THREAD

**Issue by Koc** [dustin10/VichUploaderBundle#625]
- [ ] Drop Symfony's support older than 2.7 or even 2.8
- [ ] Use options resolver for namers configuration
- [ ] Bump Doctrine version (requires for #618)
- [ ] Isolate Twig helper from templating component and make templating optional (see https://github.com/symfony/symfony/pull/13354)
- [ ] Maybe change configuration - set classes inside mapping, do not use `Uploadable` annotation (requires for #618)
- [ ] Add styleci

**Comment by garak** [comment]
Doctrine version bumped in a8a9d25a05edf32a0c935e7f2ae3f5de8dd1ddf1

**Comment by WolfgangDrescher** [comment]
I searched for `Symfony\Component\Templating` in this repo. If im correct the only place where VichUploaderBundle is using the `symfony/templating` dependency is in:

https://github.com/dustin10/VichUploaderBundle/blob/014f63c6ccf4856af134c8ddecf8e554771050eb/Templating/Helper/UploaderHelper.php#L13

But this UploaderHelper never using any methods of `Symfony\Component\Templating\Helper\Helper` (getCharset/setCharset). So if I'm correct we could just drop this class from extending the symfony templating helper dependency and remove it from composer.json.

**Comment by garak** [comment]
@WolfgangDrescher extension is needed because UploaderHelper is tagged as `templating.helper` in container (so, it's needed to give user the opportunity of using such helper in pure-PHP templates).
Rather than remove extension, we should drop UploaderHelper entirely (so, removing support for PHP templates, following same path of Symfony) and move functionality to Twig extension

**Comment by Erdou** [comment]
Hello @Koc ! Why "_Make final all classes that implement an interface_"? As it prevents to create any customized child Form Type 🤔

**Comment by garak** [comment]
> Hello @Koc ! Why "_Make final all classes that implement an interface_"? As it prevents to create any customized child Form Type 🤔

Which form type?
Generally speaking, you won't extend a class implementing an interface: just use your own class

**Comment by Erdou** [comment]
> 
> Which form type? Generally speaking, you won't extend a class implementing an interface: just use your own class

@Koc Supposing you're advocating for composition over inheritance, I noted Symfony's form types aren't final, indicating designed extendability. For example, I used that approach for the following AppImageType, aligning with some Symfony practices:


```
class AppImageType extends VichImageType
{
    protected int $maxImageSize;

    public function __construct(ParameterBagInterface $parameterBag,
                                StorageInterface $storage,
                                UploadHandler $handler,
                                PropertyMappingFactory $factory,
                                PropertyAccessorInterface $propertyAccessor = null,
                                CacheManager $cacheManager = null)
    {
        parent::__construct($storage, $handler, $factory, $propertyAccessor, $cacheManager);

        $this->maxImageSize = $parameterBag->get('uploads.image.max_size');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults([
            'required'          => false,
            'allow_delete'      => false,
            'download_uri'      => false,
            'imagine_pattern'   => 'admin_thumbnail',
            'attr'      => [
                'placeholder'       => 'Select an image',
                'accept'            => ImageUtils::getImageMimes(true),
            ],
            'constraints' => [
                new File([
                    'maxSize'           => $this->maxImageSize . 'M',
                    'mimeTypes'         => ImageUtils::getImageMimes(),
                ])
            ],
        ]);
    }
}
```

This is very handy to have a customized App Wide component.

With making classes final, while it's still possible to have this kind of custom component, we'll **force** people to code them by composition.

(Or did I miss something? ^^)

**Comment by Erdou** [comment]
Btw, I don't see any interface here (except SF's AbstractType's one ofc):

```
class VichImageType extends VichFileType

class VichFileType extends AbstractType

```

**Comment by garak** [comment]
Good points.
We can reconsider the decision and agree to remove the "final" keyword for the form types.
A PR would be appreciated.

**Comment by BoShurik** [comment]
To extend symfony form types you may use `getParent` method (see https://symfony.com/doc/current/form/create_custom_field_type.html#creating-form-types-based-on-symfony-built-in-types)
```php
class AppImageType extends AbstractType
{
    public function getParent(): string
    {
        return VichImageType::class;
    }
}
```

**Comment by Erdou** [comment]
Thanks, @BoShurik . The getParent method indeed offers a structured approach for customizing form types per Symfony’s best practices, and it's a great fit for the example I used. Regarding our discussion on using `final`, the Symfony documentation frames composition as a recommendation rather than a mandate. Notably, [none of the Symfony core form types](https://github.com/symfony/form/tree/6.3/Extension/Core/Type), are declared as final, indicating a deliberate choice to allow extension.
